services:
  # backend:
  #   build: ./backend
  #   container_name: globetrotteuse-back
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@database:5432/globetrotteuse
  #   depends_on:
  #     - database
  #   command: pnpm dev

  # frontend:
  #   build: ./frontend
  #   container_name: globetrotteuse-front
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
  #   command: pnpm dev --host 0.0.0.0

  database:
    image: postgres
    container_name: globetrotteuse-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: globetrotteuse
    ports:
      - "4500:5432"
    volumes:
            - ./db_manipulation/migration_up.sql:/migration_up.sql
            - ./db_manipulation/seed.sql:/seed.sql
      