services:
  database:
    image: postgres
    container_name: globetrotteuse-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: globetrotteuse
    ports:
      - "4500:5432"
    volumes:
    - ./db_manipulation/migration_up.sql:/docker-entrypoint-initdb.d/01-migration.sql
    - ./db_manipulation/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

