DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS travels CASCADE;
DROP TYPE IF EXISTS status CASCADE;
DROP TYPE IF EXISTS category_task CASCADE;
;DROP TABLE IF EXISTS tasks CASCADE;
DROP TYPE IF EXISTS transport_type CASCADE;
DROP TABLE IF EXISTS transports CASCADE;
DROP TABLE IF EXISTS accommodations CASCADE;
DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS participate CASCADE;

